// flow-typed signature: 5e087d66fea0554d609c5a40f716413b
// flow-typed version: <<STUB>>/typescript-compiler_v1.4.1-2/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typescript-compiler/tmp/tsreq/compiler' {
  declare module.exports: any;
}

declare module 'typescript-compiler/tmp/tsreq/compositeCompilerHost' {
  declare module.exports: any;
}

declare module 'typescript-compiler/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typescript-compiler/index' {
  declare module.exports: $Exports<'typescript-compiler'>;
}
declare module 'typescript-compiler/index.js' {
  declare module.exports: $Exports<'typescript-compiler'>;
}
declare module 'typescript-compiler/tmp/tsreq/compiler.js' {
  declare module.exports: $Exports<'typescript-compiler/tmp/tsreq/compiler'>;
}
declare module 'typescript-compiler/tmp/tsreq/compositeCompilerHost.js' {
  declare module.exports: $Exports<'typescript-compiler/tmp/tsreq/compositeCompilerHost'>;
}
declare module 'typescript-compiler/watch.js' {
  declare module.exports: $Exports<'typescript-compiler/watch'>;
}
